site_name: ROM FAMQRPA emulator Documentation

theme:
  name: readthedocs  # read_the_docs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            members_order: alphabetical
            docstring_section_style: table
            docstring_style: google
            show_root_heading: false

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - About: about.md
  - Source Code:
      - Basis Class : rom_basis.md
      - Utils : utils_rom_basis.md