try:
    import subprocess
    from concurrent.futures import ThreadPoolExecutor
except ImportError:
    print("subprocess and concurrent.futures modules are required for launching FAM runs")
from pathlib import Path
import numpy as np
try:
    from functools import cached_property
    from src.Utils_basis import cost_numba
    from src.Utils_emulator import _evaluate_PG_numba
    from src.Utils_parsers import parse_XY_numba, combine_FAM_output
    from numba import prange
except ImportError:
    print("Numba not installed.")
import re
import platform

class ROM_basis:
    """
    Class to represent the ROM_basis

    Attributes:
        omegas: The frequencies (omegas) at which the snapshots were taken, a 1D array (num_snapshots,) of complex values.
        snapshots: The snapshot data, typically a 3D array (num_snapshots, 2, entries), first dimension refers to the snapshot frequency, second dimension is for X and Y and the third dimension contains the matrix elements.
        F: The F vector associated with the snapshots (stacked F20, F02)
    """
    def __init__(self):
        """
        Initialise the ROM_basis with empty attributes. The actual data will be loaded using the load method.
        """
        self.omegas = None
        self.snapshots = None # todo consider merging omegas and snapshots together ?
        self.F = None

    def is_loaded(self):
        return self.omegas is not None and self.snapshots is not None


    def load(self, path_to_snapshot):
        """
        Loads the basis from a given snapshot file

        Args:
            path_to_snapshot: The file path to the snapshot file generated by the FAM runs, which contains the frequencies (omegas), snapshots and F vector.
        """
        from src.Utils_parsers import parse_XY_numba
        # load snapshots and omegas from file
        self.snapshots, self.omegas, self.F = parse_XY_numba(path_to_snapshot)
        return self

class data:
    """
    Class to represent the data parsed from the mean-field output file, as well as the FAM parameters.

    Attributes:
        num_proton: Number of protons in the nucleus.
        num_neutron: Number of neutrons in the nucleus.
        num_proton_wf: Number of proton wavefunctions.
        num_neutron_wf: Number of neutron wavefunctions.
        param: The parameterization used in the mean-field calculation.
        dx: The mesh spacing used in the mean-field calculation.
        size: The size of the mesh used in the mean-field calculation.
        w_min: Minimum frequency for the strength (default 0.0 MeV).
        w_max: Maximum frequency for the strength (default 20.0 MeV).
        smear: Smearing parameter (default 1.0 MeV) often called 'target smearing'.
        l: Multipolarity l of F (default 0).
        m: Multipolarity m of F (default 0).
        param_prefix: A dictionary mapping parameterization names to their prefixes used in Tantalus executables.

    """
    def __init__(self, file, fam_params=None):
        """
        Initialize the data object by parsing the mean-field output file and extracting the relevant parameters

        Attributes:
            file:  The file path to the mean-field output file, which contains the information about the nucleus and the mean-field calculation parameters.
            fam_params:  A dictionary containing the FAM parameters (w_min, w_max, smear, l, m). If None, default values will be used.
        """

        parse = self._parse_mf(file)
        self.num_proton = parse["num_proton"]
        self.num_neutron = parse["num_neutron"]
        self.num_proton_wf = parse["num_proton_wf"]
        self.num_neutron_wf = parse["num_neutron_wf"]
        self.param = parse["param"]
        self.dx = parse["dx"]
        self.size = parse["size"]

        self.param_prefix = {"BSkG2": "BXL",
                             "BSkG4": "BXL",
                             "BSkG5": "BXL-N2LO"}  # dict for parameterization prefixes @ tantalus specific

        self._fam_defaults = {
            'w_min': 0.0,
            'w_max': 20.0,
            'smear': 1.0,
            'l': 0,
            'm': 0
        }
        self.set_FAM_parameters(fam_params) # extract FAM parameters

    def set_FAM_parameters(self, fam_params):
        # FAM data
        if fam_params is None:
            fam_params = {}
        params = self._fam_defaults.copy()
        params.update(fam_params)
        # Set the attributes
        for key, value in params.items():
            setattr(self, key, value)

    def _parse_mf(self, file: str):
        # change linux path to windows path
        text = Path(file.replace("/mnt/c/", "C:/")).read_text()

        match = re.search(r"General Information\s*-+\s*(.*)", text, re.DOTALL)
        if match:
            text = match.group(1) # check below General Information

        def grab(pattern, cast):
            m = re.search(pattern, text)
            if not m:
                raise ValueError(f"Could not find pattern: {pattern}")
            return cast(m.group(1))

        return {
            "num_neutron": grab(r"N =\s*([0-9]+)", int),
            "num_proton": grab(r"Z =\s*([0-9]+)", int),
            "num_neutron_wf": grab(r"nwn\s*=\s*(\d+)", int),
            "num_proton_wf": grab(r"nwp\s*=\s*(\d+)", int),
            "param": grab(r"Parameterization name\s+(\S+)", str),
            "dx": grab(r'dx\s*=\s*([0-9.eE+-]+)', float),
            "size": grab(r'nx\s*=\s*([0-9]+)', float) * grab(r'dx\s*=\s*([0-9.eE+-]+)', float),
        }

    @property
    def prefix(self):
        return self.param_prefix[self.param]

class ROM_builder:
    """
    Class to build the ROM basis by launching FAM runs and processing the output. Can be omitted if FAM calculations are dealt with externally

    Attributes:
        data: An instance of the data class containing the mean-field and FAM parameters.
        basis: An instance of the ROM_basis class to store the snapshots and omegas.
        working_directory: The directory where FAM runs are launched and intermediate files are stored.
        TANTALUS_PATH: The path to the Tantalus installation, used for launching FAM runs.
        build_type: The method used to build the ROM basis. Can be "equidistant_1D", "greedy", "greedy_2D" or "contour".
        run_type: The method used to run the FAM calculations. Can be "generate_runfiles" to only generate the runfiles without executing them, or "default" to execute the runs immediately after generating the runfiles.
        max_num_snapshots: Maximum number of snapshots included in the basis. The iterative methods will stop once this number is reached
        path_to_meanfield_wf: The path to the mean-field wavefunction file, which is used as input for the FAM runs.
        path_to_snapshot: The path to the snapshot file generated by the FAM runs, which is used to load the ROM basis after building.
        output_dir: The directory where the processed FAM output (snapshots and omegas) is stored after merging.
        greedy_settings: A dictionary containing settings specific to the greedy build type, such as convergence criteria for selecting new snapshots.
        greedy_2D_settings: A dictionary containing settings specific to the greedy_2D build type, such as convergence criteria, threshold and maximum smearing to consider for new snapshots in the 2D greedy method.

    """
    def __init__(self,
                 path_to_meanfield_wf: str,
                 path_to_meanfield_out: str,
                 FAM,
                 tantalus_path="$HOME/code/tantalus/"):
        """
        Class to set up the ROM builder which handles the entire process of building the ROM basis

        Args:
            path_to_meanfield_wf: path to the mean-field wavefunction file
            path_to_meanfield_out: path to the mean-field output file (required to extract relevant mean-field parameters)
            FAM: a dictionary containing the FAM parameters (w_min, w_max, smear, l, m, ...). If None, default values will be used.
            tantalus_path: path to the Tantalus installation
        """
        self._DEBUG_clear_wd = True # if False, the output files are not merged and the working dir is not cleared. Only used for debugging purposes
        self._build_types = ['equidistant_1D', 'greedy', 'greedy_2D','contour']
        self._run_types = ['generate_runfiles', 'default']

        self.data = data(path_to_meanfield_out)
        self.data.set_FAM_parameters(FAM)

        #DEBUG
        if "max_num_snapshots" in FAM.keys():
            print("Max num snapshots not used! Setting it by writing to ROM_builder.max_num_snapshots!")

        self.max_num_snapshots = 5
        self.build_type = 'equidistant_1D'
        self.path_to_meanfield_wf = convert_to_linux(path_to_meanfield_wf)

        self.basis = ROM_basis() # to be loaded!!
        self.basis.load = self.load # overwrite function to have the same function but ALSO save path

        self.working_directory = self.get_base_dir().joinpath('work_dir')


        # check if Tantalus is installed, if not raise error
        self.set_TANTALUS_path(tantalus_path)

        # todo check if wf input file is valid

        self.path_to_snapshot = None # to be set
        self.run_type = 'default' # run all by default
        self.tmp_output = "TMP_SNAPSHOTS"
        self.output_dir = self.working_directory.parent.parent.joinpath("_outputs")

        self.greedy_settings = {"convergence_criterion": 0.0}
        self.greedy_2D_settings = {"convergence_criterion": 0.0, #threshold of the greedy snapshot cost cutoff
                                   "threshold": 0.1, #selecting snapshots below 0.1 relative cost
                                   "max_smearing": 20.0, } # maximum smearing to consider for new snapshots in 2D greedy


    def get_base_dir(self):
        return Path(__file__).resolve().parent

    def set_TANTALUS_path(self, path):
        """
        Overrides Tantalus path and checks for validity

        Args:
            path: string to the Tantalus installation
        """
        self.TANTALUS_PATH = path
        print(f"Checking Tantalus installation at: {self.TANTALUS_PATH}")
        if not self._check_tantalus_installation():
             raise Exception("Tantalus installation not found. No FAM runs can be launched.")


    def set_build_type(self, build_type):
        """
        Sets the build type for ROM construction and checks for validity

        Args:
            build_type: string specifying the build type. Supported types are "equidistant_1D", "greedy", "greedy_2D" and "contour".
        """
        if build_type not in self._build_types:
            raise ValueError("Unknown build type. Supported types: " + ", ".join(self._build_types))
        self.build_type = build_type


    def set_run_type(self, run_type):
        """
        Sets the run type for ROM construction and checks for validity

        Args:
            run_type: string specifying the run type. Supported types are "generate_runfiles" to only generate the runfiles without executing them, or "default" to execute the runs immediately after generating the runfiles.
        """
        if run_type not in self._run_types:
            raise ValueError("Unknown build type. Supported types: " + ", ".join(self._run_types))
        if run_type == 'generate_runfiles' and self.build_type == 'greedy':
            raise ValueError("Cannot only generate runfiles for greedy build type, as it requires iterative runs.")
        self.run_type = run_type


    def set_contour_parameters(self, n=13, R=500, r=0.1):
        """
        Sets the parameters for contour sampling. Only relevant if build_type is set to "contour".

        Args:
            n: the number of samples along the contour
            R: the outer radius of the contour
            r: the inner radius of the contour
        """
        self.contour_n = n
        self.contour_R = R
        self.contour_r = r


    def _clear_working_directory(self):
        if self.working_directory.exists():
            for item in self.working_directory.iterdir():
                if item.is_dir():
                    for subitem in item.iterdir():
                        subitem.unlink()
                    item.rmdir()
                else:
                    item.unlink()
        # make sure the working directory exists
        self.working_directory.mkdir(parents=True, exist_ok=True)


    def _create_fam_runfiles(self, omegas, output_folder="", global_iteration=0):
        """
        Create a FAM runfile for the given omegas
        """
        d = self.data
        # always create a new folder, add number if already exists
        # check if file exists
        run_folder = self.working_directory.joinpath('runfiles')

        run_folder.mkdir(parents=True, exist_ok=True)
        for iteration, omega in enumerate(omegas):
            Rew = omega.real
            Imw = omega.imag
            file = run_folder.joinpath(f"fam_run.{d.num_neutron}.{d.num_proton}.{d.num_neutron_wf}.{d.num_proton_wf}.{d.param}.{d.size}.{Rew}+{Imw}j.sh")
            file.parent.mkdir(parents=True, exist_ok=True)

            script = f"""\
#!/usr/bin/env bash
neutrons={d.num_neutron}
protons={d.num_proton}
dx={d.dx}
size={round(d.size)}
l={d.l}
m={d.m}
param="{d.param}"
pref="{d.prefix}"
logdir_name="{output_folder}"
OUT="V{iteration+global_iteration}"

# Recompute dependent variables if needed
nwn={d.num_neutron_wf}
nwp={d.num_proton_wf}
nbox=$(printf "%.0f" "$(echo "$size / $dx" | bc -l)")

# Directories HARDCODED (REFERS TO TANTALUS)
EXECDIR="{self.TANTALUS_PATH}exec"
PARAMDIR="{self.TANTALUS_PATH}parameterizations"

#1. environment variables
# clean up old log and data files. Logfile relative to workdir
wffile="{self.path_to_meanfield_wf}"
famoutfile="../$logdir_name/fam.$protons.$neutrons.$nwn.$nwp.$l.$m.$param.$size.out$OUT"
famfile="../$logdir_name/fam_data.$protons.$neutrons.$nwn.$nwp.$l.$m.$param.$size.fam$OUT"
xyfile="../$logdir_name/xy.$protons.$neutrons.$nwn.$nwp.$l.$m.$param.$size.xy$OUT"

exe="Tantalus.$pref.exe"              # full name of the mean-field executable
exefam="fam.$pref.exe"                # full name of the fam executable
param="$param"                         # name of the parameterization
workdir="{convert_to_linux(str(self.working_directory))}/work.$protons.$neutrons.$size.$nwn.$nwp$OUT"

if [ ! -d "$workdir/" ]; then
  mkdir "$workdir"
fi

cp $EXECDIR/$exe             "$workdir"/
cp $EXECDIR/$exefam          "$workdir"/
cp $PARAMDIR/"$param.param"  "$workdir"/
cd "$workdir"

if [ ! -d "../$logdir_name/" ]; then
  mkdir "../$logdir_name"
fi

# Create runtime data
cat << EOF > fam.data
&nucleus
neutrons=$neutrons, protons=$protons
/
&mesh
nx=$nbox, ny=$nbox, nz=$nbox, dx=$dx
/
&func
name_param='${{param}}'
/
&pairing
/
&evolution
maxiter=1000
/
&scfiteration
/
&wfs
nwn = $nwn, nwp = $nwp
/
&IO
InputFilename='$wffile'
OutputFilename='trash'
allowtransform=.true.
famfile='${{famfile}}'
xyfile ='${{xyfile}}' 
/
&MomentParam
/
&Cranking
/
&fam
omega={Rew}
smear={Imw}
l=$l
m=$m
maxiter=10000
fam_precision=1e-6
/
EOF

./$exefam < fam.data > $famoutfile
fam_check=$?
        """
            file.write_text(script, newline="\n")  # , encoding="utf-8")#, newline="\n")
            file.chmod(0o755)

        # if only one file is created, return just this file
        if len(omegas) == 1:
            return file
        return run_folder


    def _check_tantalus_installation(self):
        if platform.system() == "Windows":
            # Use WSL to check the Linux path
            try:
                subprocess.run(["wsl", "bash", "-c", f"test -d {self.TANTALUS_PATH}"], check=True)
                return True
            except subprocess.CalledProcessError:
                return False
        else:
            # Linux just check the path directly
            return Path(self.TANTALUS_PATH).is_dir()

    def build_snapshot_basis(self, max_workers=4, build_type=None, run_type=None):
        """
        Builds the snapshot basis by launching FAM runs according to the specified build type and run type.
        The method handles the entire process of generating FAM runfiles, executing them, and processing the output to construct the ROM basis.

        Args:
            max_workers: for parallel execution of FAM runs, only relevant for equidistant build type
            build_type: string specifying the build type. Supported types are "equidistant_1D", "greedy", "greedy_2D" and "contour". If None, the default build type set in the object is used.
            run_type: string specifying the run type. Supported types are "generate_runfiles" to only generate the runfiles without executing them, or "default" to execute the runs immediately after generating the runfiles. If None, the default run type set in the object is used.

        Returns:
            The constructed basis is saved in self.path_to_snapshot and loaded into self.basis by default.

        """

        def launch_fam(fam_runfile):
            if platform.system() == "Windows":
                # Convert Windows path to WSL path
                wsl_path = f"/mnt/{fam_runfile.drive[0].lower()}{fam_runfile.as_posix()[2:]}"
                print(f"Launching FAM with runfile: {fam_runfile}")
                subprocess.run(["bash", wsl_path], check=True)
            else:
                subprocess.run(["bash", str(fam_runfile)], check=True)

        if build_type is not None:
            self.set_build_type(build_type)
        if run_type is not None:
            self.set_run_type(run_type)

        ## clear up wd
        if self._DEBUG_clear_wd:
            self._clear_working_directory()

        d = self.data

        if self.build_type == 'equidistant_1D':
            # static basis creation
            omegas = np.linspace(d.w_min, d.w_max, num=self.max_num_snapshots) + d.smear * 1.j
            if self.basis.is_loaded():
                raise AssertionError("Basis already loaded. Cannot initiate equidistant sampling.")
            fam_runfiles = self._create_fam_runfiles(omegas, output_folder=self.tmp_output)

            if self.run_type == 'default':
                dir = self.working_directory.joinpath(self.tmp_output)
                dir.mkdir(parents=True, exist_ok=True)

                with ThreadPoolExecutor(max_workers=max_workers) as executor:
                    executor.map(launch_fam, fam_runfiles.iterdir())

                print("FAM launch completed, merging ...")
                self.path_to_snapshot = combine_FAM_output(directory=fr"{dir}",
                                                           output_dir=self.output_dir)

        elif self.build_type == 'contour':
            ### start calculations to allow contour integration!
            if self.basis.is_loaded():
                print("Basis already loaded. Adding samples")
            # check if contour parameters are set
            if not hasattr(self, 'contour_n') or not hasattr(self, 'contour_R') or not hasattr(self, 'contour_r'):
                raise ValueError("Contour parameters not set. Please set contour parameters before building contour basis.")
            samples = [self.contour_R * np.cos(arg) + 1j * self.contour_R * np.sin(arg) for arg in np.linspace(0, np.pi/2, self.contour_n)]

            fam_runfiles = self._create_fam_runfiles(samples, output_folder=self.tmp_output)
            if self.run_type == 'default':
                with ThreadPoolExecutor(max_workers=max_workers) as executor:
                    executor.map(launch_fam, fam_runfiles.iterdir())
                print("FAM launch completed, merging ...")
                self.path_to_snapshot = combine_FAM_output(directory=fr"{self.working_directory.joinpath(self.tmp_output)}",
                                                           output_dir=self.output_dir,
                                                           master_file=self.path_to_snapshot if self.basis.is_loaded() else None)

        elif self.build_type == 'greedy':
            # iterative basis creation
            W_scan = np.linspace(d.w_min, d.w_max, num=2000) + d.smear * 1.j
            if not self.basis.is_loaded():
                initial_vectors = 2
                # choose two snapshots, say at 0.25 and 0.75 from the spectrum
                w1 = 0.25*(d.w_max - d.w_min) + d.smear * 1.j
                w2 = 0.75*(d.w_max - d.w_min) + d.smear * 1.j

                # initiate two FAM runs
                fam_runfiles = self._create_fam_runfiles([w1,w2], output_folder=self.tmp_output)
                #base_dir = Path(f"src/work_dir/{self.tmp_output}")
                base_dir = self.working_directory.joinpath(self.tmp_output)

                base_dir.mkdir(parents=True, exist_ok=True)

                with ThreadPoolExecutor(max_workers=2) as executor:
                    executor.map(launch_fam, fam_runfiles.iterdir())

                print("Initial FAM launch completed.")
                self.path_to_snapshot = combine_FAM_output(directory=fr"{self.working_directory.joinpath(self.tmp_output)}",
                                                      output_dir=self.output_dir,
                                                      output_name='')
            else:
                initial_vectors = len(self.basis.omegas)
                print(f"Initial basis loaded. Continuing to add {self.max_num_snapshots-initial_vectors} vectors")

            snapshots, snapshot_omegas, F = parse_XY_numba(self.path_to_snapshot)

            ### greedy loop
            GREEDY_COST = np.inf
            while GREEDY_COST > self.greedy_settings["convergence_criterion"] and len(snapshot_omegas) < self.max_num_snapshots:
                FdF = F.conj().T @ F

                COSTS = np.zeros(len(W_scan))

                X = snapshots[:, 0, :]
                Y = snapshots[:, 1, :]

                MXdF = np.concatenate((X.conj(), -Y.conj()), axis=1) @ F
                XMMX = X.conj() @ X.T + Y.conj() @ Y.T

                _, alphas = _evaluate_PG_numba(W_scan, snapshot_omegas, X, Y, F)

                for idx in prange(len(W_scan)):
                    omega_test = W_scan[idx]
                    alpha = alphas[idx]

                    COSTS[idx] = cost_numba(omega=omega_test,
                                      alpha=alpha,
                                      FdF=FdF, MXdF=MXdF, XMMX=XMMX, F_norm=np.linalg.norm(F),
                                      snapshot_omegas=snapshot_omegas)

                # ADD NEW SNAPSHOT WITH MAX COST
                max_cost_idx = np.argmax(COSTS)

                print('Initiating new FAM run for new snapshot: ', W_scan[max_cost_idx])
                # launch new FAM run for new snapshot
                fam_runfile = self._create_fam_runfiles([W_scan[max_cost_idx]],
                                                        output_folder=self.tmp_output,
                                                        global_iteration=len(snapshot_omegas)+1)
                base_dir = Path(f"src/work_dir/{self.tmp_output}")
                base_dir.mkdir(parents=True, exist_ok=True)

                launch_fam(fam_runfile)
                print("FAM launch completed for new snapshot.")

                self.path_to_snapshot = combine_FAM_output(directory=fr"{self.working_directory.joinpath(self.tmp_output)}",
                                                       output_dir=self.output_dir,
                                                       master_file=self.path_to_snapshot if self.basis.is_loaded() else None)

                # DO WE NEED TO PARSE HERE? OR CAN WE JUST APPEND? @emma #TODO
                snapshots, snapshot_omegas, F = parse_XY_numba(self.path_to_snapshot)

                GREEDY_COST = np.max(COSTS)

        elif self.build_type == 'greedy_2D':
            # Define the W_scan @ the target smearing
            W_scan = np.linspace(d.w_min, d.w_max, num=2000) + d.smear * 1.j

            initial_vectors = 9
            if not self.basis.is_loaded():
                # choose FIVE snapshots, say at 0.25 and 0.75 from the spectrum @ 10 times the target smearing !
                ws = np.linspace( 0.25 * (d.w_max - d.w_min) ,  0.75 * (d.w_max - d.w_min), initial_vectors) + 10 * d.smear * 1.j
                fam_runfiles = self._create_fam_runfiles(ws, output_folder=self.tmp_output)
                self.working_directory.joinpath(self.tmp_output).mkdir(parents=True, exist_ok=True)

                with ThreadPoolExecutor(max_workers=5) as executor:
                    executor.map(launch_fam, fam_runfiles.iterdir())

                print("Initial FAM launch completed.")
                self.path_to_snapshot = combine_FAM_output(
                    directory=fr"{self.working_directory.joinpath(self.tmp_output)}",
                    output_dir=self.output_dir,
                    output_name='')
            else:
                initial_vectors = len(self.basis.omegas)
                print(
                    f"Initial basis loaded. Continuing to add {self.max_num_snapshots - initial_vectors} vectors")

            # DO WE NEED TO PARSE HERE?? @emma #TODO
            snapshots, snapshot_omegas, F = parse_XY_numba(self.path_to_snapshot)

            ### greedy loop
            GREEDY_COST = np.inf
            while GREEDY_COST > self.greedy_2D_settings["convergence_criterion"] and len(snapshot_omegas) < self.max_num_snapshots:
                FdF = F.conj().T @ F

                COSTS = np.zeros(len(W_scan))

                X = snapshots[:, 0, :]
                Y = snapshots[:, 1, :]

                MXdF = np.concatenate((X.conj(), -Y.conj()), axis=1) @ F
                XMMX = X.conj() @ X.T + Y.conj() @ Y.T

                _, alphas = _evaluate_PG_numba(W_scan, snapshot_omegas, X, Y, F)

                for idx in prange(len(W_scan)):
                    omega_test = W_scan[idx]
                    alpha = alphas[idx]

                    COSTS[idx] = cost_numba(omega=omega_test,
                                            alpha=alpha,
                                            FdF=FdF, MXdF=MXdF, XMMX=XMMX, F_norm=np.linalg.norm(F),
                                            snapshot_omegas=snapshot_omegas)

                max_cost_idx = np.argmax(COSTS)

                # now, scan this omega value along the complex axis, and find the "sub"-optimal omega value
                H_scan = np.real(W_scan[max_cost_idx]) + np.linspace(1, self.greedy_2D_settings["max_smearing"],200)*1j*d.smear
                COSTS_H = np.zeros(len(H_scan))
                _, alphas = _evaluate_PG_numba(H_scan, snapshot_omegas, X, Y, F)
                for idx in prange(len(H_scan)):
                    omega_test = H_scan[idx]
                    alpha = alphas[idx]
                    COSTS_H[idx] = cost_numba(omega=omega_test,
                                            alpha=alpha,
                                            FdF=FdF, MXdF=MXdF, XMMX=XMMX, F_norm=np.linalg.norm(F),
                                            snapshot_omegas=snapshot_omegas)

                # find the maximal cost in H but below a threshold
                COSTS_H = COSTS_H / np.max(COSTS_H)  # normalise wrt "highest" one
                COSTS_H = np.where(COSTS_H > self.greedy_2D_settings["threshold"], 0.0, COSTS_H)
                if np.all(COSTS_H == 0.0):
                    print("No new snapshot found above threshold, adding the one with largest smearing")
                    max_cost_idx_H = -1
                else:
                    max_cost_idx_H = np.argmax(COSTS_H)
                SUB_OPTIMAL_OMEGA = H_scan[max_cost_idx_H]
                print("Selected : ", SUB_OPTIMAL_OMEGA)

                # launch new FAM run for new snapshot
                fam_runfile = self._create_fam_runfiles([SUB_OPTIMAL_OMEGA],
                                                        output_folder=self.tmp_output,
                                                        global_iteration=len(snapshot_omegas)+1)
                self.working_directory.joinpath(self.tmp_output).mkdir(parents=True, exist_ok=True)

                launch_fam(fam_runfile)

                print("FAM launch completed for new snapshot.")
                self.path_to_snapshot = combine_FAM_output(
                    directory=fr"{self.working_directory.joinpath(self.tmp_output)}",
                    output_dir=self.output_dir,
                    master_file=self.path_to_snapshot if self.basis.is_loaded() else None)

                # DO WE NEED TO PARSE HERE? OR CAN WE JUST APPEND? @emma #TODO
                snapshots, snapshot_omegas, F = parse_XY_numba(self.path_to_snapshot)

                GREEDY_COST = np.max(COSTS) # save the cost evaluated at target smearing

        else: raise ValueError("Unknown build type: " + self.build_type+". Supported types: "+  str(self._build_types))

        # clean up and load basis
        if not self._DEBUG_clear_wd:
            print("Clearing wd is disabled.")

        elif self.run_type == 'default':
            self._clear_working_directory()
            self.basis.load(self.path_to_snapshot)
            print("Basis loaded.")
        return


    def load(self, path_to_snapshot):
        from src.Utils_parsers import parse_XY_numba
        try:
            # load snapshots and omegas from file
            self.basis.snapshots, self.basis.omegas, self.basis.F = parse_XY_numba(path_to_snapshot)
            self.path_to_snapshot = Path(path_to_snapshot)
        except FileNotFoundError:
            raise FileNotFoundError(f"Could not find snapshot {path_to_snapshot}.")

def convert_to_linux(path: str) -> str:
    """
    Helper function to convert Windows paths to Linux paths for WSL compatibility. If the path is already in Linux format, it is returned unchanged.

    Arguments:
        path: sting representing the file path to be converted.

    Returns:
        A string representing the converted file path in Linux format.

    """
    if platform.system() == "Windows":
        path = path.replace("\\", "/")
        if path[1] == ":":
            drive = path[0].lower()
            rest = path[2:]
            rest = rest.lstrip("/")
            return f"/mnt/{drive}/{rest}"
        else:
            return path
    else:
        return path